In [3]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv("Crash_Analysis_System_(CAS)_data.csv")

In [5]:

df.head(5)

,X,Y,OBJECTID,advisorySpeed,areaUnitID,bicycle,bridge,bus,carStationWagon,cliffBank,...,train,tree,truck,unknownVehicleType,urban,vanOrUtility,vehicle,waterRiver,weatherA,weatherB
0,1665025.0,6039555.0,1,NaN,504501.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,Open,1.0,0.0,0.0,Fine,Null
1,1703417.0,5680183.0,2,NaN,551013.0,0.0,NaN,0.0,2.0,NaN,...,NaN,NaN,0.0,0.0,Open,0.0,NaN,NaN,Fine,Null
2,1890473.0,5820767.0,3,NaN,536203.0,0.0,NaN,0.0,2.0,NaN,...,NaN,NaN,0.0,0.0,Open,0.0,NaN,NaN,Fine,Null
3,1757235.0,5920245.0,4,NaN,514102.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,1.0,0.0,Urban,0.0,NaN,NaN,Fine,Null
4,1880716.0,5830144.0,5,NaN,536810.0,1.0,NaN,0.0,1.0,NaN,...,NaN,NaN,0.0,0.0,Urban,0.0,NaN,NaN,Fine,Null

In [6]:
df.size

50803848

In [7]:
df.shape

(705609, 72)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705609 entries, 0 to 705608
Data columns (total 72 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   X                          705609 non-null  float64
 1   Y                          705609 non-null  float64
 2   OBJECTID                   705609 non-null  int64
 3   advisorySpeed              27684 non-null   float64
 4   areaUnitID                 705470 non-null  float64
 5   bicycle                    705604 non-null  float64
 6   bridge                     301613 non-null  float64
 7   bus                        705604 non-null  float64
 8   carStationWagon            705604 non-null  float64
 9   cliffBank                  301613 non-null  float64
 10  crashDirectionDescription  705609 non-null  object
 11  crashFinancialYear         705609 non-null  object
 12  crashLocation1             705609 non-null  object
 13  crashLocation2             703595 non-null  object
 14  crashRoadSideRoad          0 non-null       float64
 15  crashSeverity              705609 non-null  object
 16  crashSHDescription         705471 non-null  object
 17  crashYear                  705609 non-null  int64
 18  debris                     301613 non-null  float64
 19  directionRoleDescription   705540 non-null  object
 20  ditch                      301613 non-null  float64
 21  fatalCount                 705497 non-null  float64
 22  fence                      301613 non-null  float64
 23  flatHill                   705609 non-null  object
 24  guardRail                  301613 non-null  float64
 25  holiday                    38774 non-null   object
 26  houseOrBuilding            301613 non-null  float64
 27  intersection               0 non-null       float64
 28  kerb                       301613 non-null  float64
 29  light                      705609 non-null  object
 30  meshblockId                705470 non-null  float64
 31  minorInjuryCount           705497 non-null  float64
 32  moped                      705604 non-null  float64
 33  motorcycle                 705604 non-null  float64
 34  NumberOfLanes              703296 non-null  float64
 35  objectThrownOrDropped      301613 non-null  float64
 36  otherObject                301613 non-null  float64
 37  otherVehicleType           705604 non-null  float64
 38  overBank                   301613 non-null  float64
 39  parkedVehicle              301613 non-null  float64
 40  pedestrian                 23695 non-null   float64
 41  phoneBoxEtc                301613 non-null  float64
 42  postOrPole                 301613 non-null  float64
 43  region                     702785 non-null  object
 44  roadCharacter              705609 non-null  object
 45  roadLane                   705609 non-null  object
 46  roadSurface                705609 non-null  object
 47  roadworks                  301613 non-null  float64
 48  schoolBus                  705604 non-null  float64
 49  seriousInjuryCount         705497 non-null  float64
 50  slipOrFlood                301613 non-null  float64
 51  speedLimit                 704047 non-null  float64
 52  strayAnimal                301613 non-null  float64
 53  streetLight                583890 non-null  object
 54  suv                        705604 non-null  float64
 55  taxi                       705604 non-null  float64
 56  temporarySpeedLimit        14757 non-null   float64
 57  tlaId                      705469 non-null  float64
 58  tlaName                    705469 non-null  object
 59  trafficControl             705609 non-null  object
 60  trafficIsland              301613 non-null  float64
 61  trafficSign                301613 non-null  float64
 62  train                      301613 non-null  float64
 63  tree                       301613 non-null  float64
 64  truck                      705604 non-null  float64
 65  unknownVehicleType         705604 non-null  float64
 66  urban                      705609 non-null  object
 67  vanOrUtility               705604 non-null  float64
 68  vehicle                    301613 non-null  float64
 69  waterRiver                 301613 non-null  float64
 70  weatherA                   705609 non-null  object
 71  weatherB                   701873 non-null  object
dtypes: float64(50), int64(2), object(20)
memory usage: 387.6+ MB

In [9]:
df.describe()

,X,Y,OBJECTID,advisorySpeed,areaUnitID,bicycle,bridge,bus,carStationWagon,cliffBank,...,tlaId,trafficIsland,trafficSign,train,tree,truck,unknownVehicleType,vanOrUtility,vehicle,waterRiver
count,7.056090e+05,7.056090e+05,705609.000000,27684.000000,705470.000000,705604.000000,301613.000000,705604.000000,705604.000000,301613.000000,...,705469.000000,301613.000000,301613.000000,301613.000000,301613.000000,705604.000000,705604.000000,705604.000000,301613.000000,301613.000000
mean,1.721543e+06,5.642569e+06,352805.000000,54.184547,546601.574620,0.029354,0.012536,0.016539,1.246426,0.106259,...,51.737947,0.027621,0.050319,0.001114,0.104303,0.078215,0.007292,0.178867,0.021322,0.008650
std,1.542712e+05,3.293272e+05,203691.917384,17.788413,32428.082856,0.172500,0.112564,0.129083,0.787160,0.309629,...,24.144270,0.165737,0.221017,0.033358,0.312062,0.280569,0.087234,0.413957,0.147409,0.092925
min,1.166279e+06,4.721798e+06,1.000000,15.000000,500100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.699830e+06,5.433618e+06,176403.000000,45.000000,520301.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.757663e+06,5.793346e+06,352805.000000,55.000000,536821.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.796391e+06,5.913289e+06,529207.000000,65.000000,573700.000000,0.000000,0.000000,0.000000,2.000000,0.000000,...,76.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.465388e+06,6.190024e+06,705609.000000,95.000000,626801.000000,5.000000,4.000000,3.000000,16.000000,3.000000,...,76.000000,4.000000,4.000000,1.000000,4.000000,5.000000,3.000000,6.000000,5.000000,2.000000

In [10]:
print(df.columns.tolist())
print(f"\nTotal Columns : {len(df.columns)}")

['X', 'Y', 'OBJECTID', 'advisorySpeed', 'areaUnitID', 'bicycle', 'bridge', 'bus', 'carStationWagon', 'cliffBank', 'crashDirectionDescription', 'crashFinancialYear', 'crashLocation1', 'crashLocation2', 'crashRoadSideRoad', 'crashSeverity', 'crashSHDescription', 'crashYear', 'debris', 'directionRoleDescription', 'ditch', 'fatalCount', 'fence', 'flatHill', 'guardRail', 'holiday', 'houseOrBuilding', 'intersection', 'kerb', 'light', 'meshblockId', 'minorInjuryCount', 'moped', 'motorcycle', 'NumberOfLanes', 'objectThrownOrDropped', 'otherObject', 'otherVehicleType', 'overBank', 'parkedVehicle', 'pedestrian', 'phoneBoxEtc', 'postOrPole', 'region', 'roadCharacter', 'roadLane', 'roadSurface', 'roadworks', 'schoolBus', 'seriousInjuryCount', 'slipOrFlood', 'speedLimit', 'strayAnimal', 'streetLight', 'suv', 'taxi', 'temporarySpeedLimit', 'tlaId', 'tlaName', 'trafficControl', 'trafficIsland', 'trafficSign', 'train', 'tree', 'truck', 'unknownVehicleType', 'urban', 'vanOrUtility', 'vehicle', 'waterRiver', 'weatherA', 'weatherB']

Total Columns : 72

In [17]:
#How many unique values does crashSeverity have, and what are they? (.unique())
print(df['crashYear'].unique())

[2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019
 2020 2021 2022 2023 2024 2025 2026]

In [19]:
 #5. How many crashes happened in each year? Use .value_counts() on crashYear.
df['crashYear'].value_counts().sort_index()

crashYear
2006    39778
2007    41661
2008    39535
2009    38247
2010    36870
2011    32450
2012    30443
2013    30109
2014    29784
2015    32104
2016    37250
2017    39314
2018    38470
2019    36931
2020    32820
2021    34156
2022    31252
2023    31511
2024    29334
2025    29017
2026    14573
Name: count, dtype: int64

In [22]:
#What's the minimum and maximum value in crashYear? (.min(), .max())
print(df['crashYear'].min())
print(df['crashYear'].max())

2006
2026

In [25]:
#  Fatal crash count

fatal = df[df['crashSeverity'] == 'Fatal Crash']
print(len(fatal))
print()

6182

In [26]:
#Average speedLimit for fatal crashes

print(fatal['speedLimit'].mean())
print()

85.20454545454545